### ISSUE TITLE
Create GitHub pages / mkdocs workflow

### ISSUE THREAD

**Issue by HarryTWhite** [EXA-UQ/EXAUQ-Toolbox#352]
### Motivation
--------------------

As mentioned in iss: #315 and PR: #341, we should have some automation in place for rebuilding our API documentation when changes are made. We need to decide if we do this on push to all of dev/main/releases or if we just do it on push to main/releases. 

Either way, this is also linked to #289 as we can't set up the workflow until GitHub pages have been set up. 

### Acceptance criteria
--------------------------

Set up the appropriate workflows for GitHub pages updates / mkdocs building. 

The following workflow from the [mkdocs material](https://squidfunk.github.io/mkdocs-material/publishing-your-site/) site may be useful for GitHub pages. For the mkdocs build, it could look something like: 

```yaml
name: Rebuild docs
run-name: "Rebuild docs upon ${{ github.event_name }} from ${{ github.ref_name }}"
on:
  push:
    branches: [ "dev", "main", "releases/*" ]
  repository_dispatch:
  workflow_dispatch:
  workflow_call:

jobs: 
    Rebuild_docs:
        name: build-mkdocs
        runs-on: ubuntu-latest
        strategy: 
            fail-fast: True
        steps:
        - uses: actions/checkout@v3
          with:
            ref: dev
        - uses: actions/setup-python@v4
          with:
            python-version: '3.10'
        - name: Install Poetry
          uses: abatilo/actions-poetry@v2
        - name: Install dependencies
          run: rm -r poetry.lock && poetry install --with=dev
        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v4
          with:
            commit-message: 'Rebuild mkdocs'
            branch: Update-API-Documentation
            title: 'Update-API-Documentation'
            body: |
              Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action.
              
              Updates and rebuild mkdocs to ensure API documentation is up to date with codebase.  
          # Prevents errors if there are no changes to commit
          continue-on-error: true
```

which will create a PR upon any push to dev/main/releases etc to then update the docs. (This will trigger all the tests etc. running again so we should keep a note of minutes etc.)
